CFLAGS = -Wall -pedantic -Werror -Wextra -std=gnu89

betty-all:
	betty lists.h 0-print_listint.c

t0: lists.h 0-main.c
	gcc $(CFLAFS) 0-main.c 0-print_listint.c -o a

t1: lists.h 1-main.c
	gcc $(CFLAFS) 1-main.c 1-listint_len.c -o b

t2: lists.h 2-main.c
	gcc $(CFLAFS) 2-main.c 2-add_nodeint.c 0-print_listint.c -o c

t3: lists.h 3-main.c
	gcc $(CFLAFS) 3-main.c 3-add_nodeint_end.c 0-print_listint.c -o

t4: lists.h 4-main.c
	gcc $(CFLAFS) 4-main.c 3-add_nodeint_end.c 0-print_listint.c 4-free_listint.c -o e

t5: lists.h 5-main.c
	gcc $(CFLAFS) 5-main.c 3-add_nodeint_end.c 0-print_listint.c 5-free_listint2.c -o f

t6: lists.h 6-main.c
	gcc $(CFLAFS) 6-main.c 3-add_nodeint_end.c 0-print_listint.c 5-free_listint2.c 6-pop_listint.c -o g

t7: lists.h 7-main.c
	gcc $(CFLAFS) 7-main.c 3-add_nodeint_end.c 0-print_listint.c 5-free_listint2.c 7-get_nodeint.c -o h

t8: lists.h 8-main.c
	gcc $(CFLAFS) 8-main.c 3-add_nodeint_end.c 5-free_listint2.c 8-sum_listint.c -o i

t9: lists.h 9-main.c
	gcc $(CFLAFS) 9-main.c 3-add_nodeint_end.c 0-print_listint.c 5-free_listint2.c 9-insert_nodeint.c -o j

t10: lists.h 10-main.c
	gcc $(CFLAFS) 10-main.c 3-add_nodeint_end.c 0-print_listint.c 5-free_listint2.c 10-delete_nodeint.c -o k

